server:
  host: "0.0.0.0"
  port: 8080

mongodb:
  uri: "mongodb://localhost:27017"
  database: "production"
  username: ""
  password: ""
  timeout: 30

search:
  index_path: "./indexes"
  batch_size: 1000
  flush_interval: 30
  sync_state_path: "./sync_state.json"

indexes:
  - name: "tags"
    database: "production"
    collection: "tags"
    definition:
      mappings:
        dynamic: true
        fields:
          - name: "tag_name_search"
            field: "tag_name"
            type: "text"
            analyzer: "standard"
          - name: "tag_name_keyword"
            field: "tag_name"
            type: "keyword"
          - name: "source"
            field: "source"
            type: "keyword"
            facet: true
          - name: "created_at"
            field: "created_at"
            type: "date"
          - name: "user_count"
            field: "user_count"
            type: "numeric"
            facet: true
