server:
  host: "0.0.0.0"
  port: 8080
  username: "admin"  # Username for API authentication (optional)
  password: "secret" # Password for API authentication (optional)

mongodb:
  uri: "mongodb://localhost:27017"
  database: "production"
  username: ""
  password: ""
  timeout: 30

search:
  index_path: "./indexes"
  batch_size: 1000
  flush_interval: 30
  sync_state_path: "./sync_state.json"

cluster:
  enabled: false
  node_id: "node-1"
  bind_addr: "0.0.0.0:7946"
  raft_port: 7946
  raft_dir: "./raft"
  bootstrap: false # Set to true only for the first node in the cluster
  join_addr: [] # Add existing cluster node addresses here when joining
  data_dir: "./cluster_data"

indexes:
  - name: "tags"
    database: "production"
    collection: "tags"
    distribution:
      replicas: 1
      shards: 1
    definition:
      mappings:
        dynamic: true
        fields:
          - name: "tag_name_search"
            field: "tag_name"
            type: "text"
            analyzer: "standard"
          - name: "tag_name_keyword"
            field: "tag_name"
            type: "keyword"
          - name: "source"
            field: "source"
            type: "keyword"
            facet: true
          - name: "created_at"
            field: "created_at"
            type: "date"
          - name: "user_count"
            field: "user_count"
            type: "numeric"
            facet: true
