apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-atlas-search.configMapName" . }}
  labels:
    {{- include "open-atlas-search.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      port: {{ .Values.config.server.port }}
      {{- if .Values.authentication.enabled }}
      # Authentication credentials will be provided via environment variables
      # OAS_SERVER_USERNAME and OAS_SERVER_PASSWORD
      {{- end }}
    mongodb:
      uri: {{ .Values.config.mongodb.uri | quote }}
    search:
      index_path: {{ .Values.config.search.index_path | quote }}
    {{- if eq .Values.deploymentMode "cluster" }}
    cluster:
      enabled: true
      bind_addr: {{ .Values.cluster.bindAddr | quote }}
      raft_port: {{ .Values.cluster.raftPort }}
      raft_dir: {{ .Values.cluster.raftDir | quote }}
      bootstrap: {{ .Values.cluster.bootstrap }}
      {{- if .Values.cluster.joinAddr }}
      join_addr:
{{ toYaml .Values.cluster.joinAddr | indent 8 }}
      {{- end }}
      data_dir: {{ .Values.cluster.dataDir | quote }}
      grpc_port: {{ .Values.cluster.grpcPort }}
    {{- else }}
    cluster:
      enabled: false
    {{- end }}
