{{- if eq .Values.deploymentMode "cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-atlas-search.fullname" . }}-headless
  labels:
    {{- include "open-atlas-search.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  selector:
    {{- include "open-atlas-search.selectorLabels" . | nindent 4 }}
  ports:
    - name: raft
      port: {{ .Values.cluster.raftPort }}
      protocol: TCP
    - name: grpc
      port: {{ .Values.cluster.grpcPort }}
      protocol: TCP
{{- end }}

