{{- if and .Values.persistence.enabled (eq .Values.deploymentMode "standalone") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "open-atlas-search.pvcName" . }}
  labels:
    {{- include "open-atlas-search.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
