apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-atlas-search.fullname" . }}
  labels:
    {{- include "open-atlas-search.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "open-atlas-search.selectorLabels" . | nindent 4 }}
