name: package-helm-chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Lint Helm chart
        run: helm lint ./charts/open-atlas-search

      - name: Template Helm chart (Standalone)
        run: |
          helm template test-standalone ./charts/open-atlas-search \
            --set deploymentMode=standalone \
            --set image.repository=test/open-atlas-search

      - name: Template Helm chart (Cluster)
        run: |
          helm template test-cluster ./charts/open-atlas-search \
            --set deploymentMode=cluster \
            --set image.repository=test/open-atlas-search

  package-helm-chart:
    needs: lint-and-test
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yq
        uses: mikefarah/yq@v4.44.1

      - name: Set environment variables
        id: set-variables
        run: |
          echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(yq -r .version ./charts/open-atlas-search/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Env variable output
        id: test-variables
        run: |
          echo ${{ steps.set-variables.outputs.REPOSITORY }}
          echo ${{ steps.set-variables.outputs.VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Package and push helm chart
        run: |
          helm package ./charts/open-atlas-search --version ${{ steps.set-variables.outputs.VERSION }}
          helm push ./open-atlas-search-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ steps.set-variables.outputs.REPOSITORY }}/charts

  publish-helm-chart:
    needs: lint-and-test
    permissions:
      id-token: write
      packages: write
      contents: write
      actions: read
      deployments: read
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Helm chart to GitHub Pages
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          charts_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}
          branch: gh-pages
          commit_username: ${{ github.actor }}
          commit_email: ${{ github.actor }}@users.noreply.github.com
          linting: off

      - name: Repository information
        run: |
          echo "📦 Helm chart published to multiple locations!"
          echo ""
          echo "🌐 GitHub Pages Repository: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "📦 OCI Registry: ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/charts"
          echo ""
          echo "🚀 Getting Started (GitHub Pages):"
          echo "   helm repo add open-atlas-search https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "   helm repo update"
          echo "   helm install my-search open-atlas-search/open-atlas-search"
          echo ""
          echo "🚀 Getting Started (OCI Registry):"
          echo "   helm install my-search oci://ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/charts/open-atlas-search"
          echo ""
          echo "📚 Documentation: https://github.com/${{ github.repository }}/blob/master/charts/open-atlas-search/README.md"
