# Default values for open-atlas-search
# Deployment mode: "standalone" or "cluster"
deploymentMode: "standalone"

# For standalone mode
replicaCount: 3

# For cluster mode
statefulSet:
  replicas: 3

image:
  repository: davidschrooten/open-atlas-search
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: search.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: open-atlas-search-tls
      hosts:
        - search.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Persistent storage for search indexes
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /data

# Application configuration
config:
  server:
    port: 3000
  mongodb:
    uri: "mongodb://mongodb:27017"
  search:
    index_path: "/data/indexes"

# Cluster settings (automatically enabled when deploymentMode is "cluster")
cluster:
  # Cluster ports
  raftPort: 7946
  grpcPort: 50051
  # Storage paths
  raftDir: "/data/raft"
  dataDir: "/data/cluster"
  # Bootstrap settings (first node should have bootstrap: true)
  bootstrap: false
  # Join existing cluster (list of existing node addresses)
  joinAddr: []
  # Node configuration
  bindAddr: "0.0.0.0:7946"

# Environment variables
env: []
  # - name: LOG_LEVEL
  #   value: "info"

# Additional environment variables from secrets/configmaps
envFrom: []
  # - configMapRef:
  #     name: special-config
  # - secretRef:
  #     name: special-secret
