# Example values for Open Atlas Search with Authentication Enabled
# This file demonstrates how to configure authentication for the Helm chart

# Use standalone deployment mode
deploymentMode: "standalone"
replicaCount: 1

image:
  repository: davidschrooten/open-atlas-search
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Disable ingress for this example
ingress:
  enabled: false

# Application configuration
config:
  server:
    port: 3000
  mongodb:
    uri: "mongodb://mongodb:27017"
  search:
    index_path: "/data/indexes"

# Enable authentication with username and password
authentication:
  enabled: true
  username: "admin"
  password: "secret123"

# You can alternatively use an existing secret
# authentication:
#   enabled: true
#   existingSecret: "my-auth-secret"
#   secretKeys:
#     username: "username"
#     password: "password"

# Disable persistence for this example
persistence:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
